# Configuration file for mosemm_products.
[general]
    # General settings.
    #
    #   output_period_to_export: string, list
    #       The temporal period for which the monitoring products will
    #       be generated and exported. To export results of only one
    #       monthly period, enter the month string in the format
    #       "YYYYMM"; for example, to export the maps of February of
    #       2018, enter output_period_to_export = "201802". To export
    #       the results of more than one period (month), enter the
    #       first and last periods of interes in a list; for example,
    #       to export the maps from February of 2018 to January of
    #       2019, enter output_period_to_export = ["201802", "201901"].
    #       To export results of all periods analyzed (from January of
    #       1980, to present), enter output_period_to_export = "all".
    #       Finally, if only the last period is wanted, enter
    #       output_period_to_export = "last".
    #   overwrite: bool
    #       Wether to overwrite (overwrite = true) of not (overwrite =
    #       false) the existent files.
    #

    input_data_dir = '/media/storage/OneDrive/proyectos/multiannual/mosemm/pysdi_output'
    overwrite = false  # Still not implemented.
    output_prefix = ''
    NODATA = -32768

[intensity_maps]
    export = true
    input_data_fpatt = '**/*.nc4'
    output_period_to_export = "last"
    output_dir = '/media/storage/OneDrive/proyectos/multiannual/mosemm/outputs_mapas'

[magnitude_maps]
    export = true
    input_data_fpatt = '**/*SPI-01*.nc4'
    output_period_to_export = "last"
    output_dir = '/media/storage/OneDrive/proyectos/multiannual/mosemm/outputs_mapas'

[time_series]
    export = true
    input_data_fpatt = '**/*SPI-01*.nc4'
    input_vmaps_dir = '/media/storage/OneDrive/proyectos/multiannual/mosemm/principal/moseq/moseq/regions'
    input_mapfile_patt = '**/*estados.shp'
    output_period_to_export = "all"
    output_dir = '/media/storage/OneDrive/proyectos/multiannual/mosemm/outputs_series'

[reports]
    export = true
    input_data_fpatt = '**/*SPI-01*.nc4'
    input_regions_dir = '/media/storage/OneDrive/proyectos/multiannual/mosemm/principal/moseq/moseq/regions'
    input_mapfile_patt = '**/*municipios.shp'
    output_period_to_export = "last"
    output_dir = '/media/storage/OneDrive/proyectos/multiannual/mosemm/outputs_reportes'
